spring.application.name=travel2

# 서버 포트 지정
server.port=8080

# devtools 설정
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# 보안파일 추가
spring.profiles.include = secret

# JPA 설정(추후 변경 db 지정시)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# 마이바티스 설정 (추후 변경)
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml

# batch 설정
spring.batch.job.enabled=false

# thymeleaf 설정
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
# spring.thymeleaf.suffix=.html
# spring.thymeleaf.encoding=UTF-8
# spring.thymeleaf.mode=HTML5

# 로깅 파일 설정
logging.config = classpath:logback-spring.xml

# 파일 업로드 설정!
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 50MB

# 파일 업로드 경로( 절대경로로 지정 )
file.upload-dir=/DATA/travel/upload
file.temp-upload-dir=/DATA/travel/temp
